name: itslive-ingest
channels:
  - conda-forge
dependencies:
  - python=3.13
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - boto3>=1.17.0
  - python-multipart>=0.0.5
  - psycopg2
  - sqlalchemy
  - awscli
  - jq
  - stac-geoparquet
  - fastparquet
  - pyarrow
  - pystac
  - geojson
  - pip
  - pip:
    - pypgstac[psycopg]
platforms:
  - linux-64
